plugins {
    alias(libs.plugins.solo.jvm.library)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.pitest)
    `java-test-fixtures`
}

dependencies {
    api(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.serialization.json)

    testFixturesImplementation(libs.kotlinx.coroutines.core)
}

kover {
    reports {
        verify {
            rule("Domain line coverage") {
                minBound(90)
            }
        }
    }
}

pitest {
    junit5PluginVersion.set(libs.versions.pitestJunit5)
    targetClasses.set(listOf("io.github.vinaooo.solo.domain.*"))
    // Generated by kotlinx.serialization; covered by round-trip tests instead.
    excludedClasses.set(listOf("*\$\$serializer"))
    timeoutConstInMillis.set(10_000)
    threads.set(2)
    jvmArgs.set(listOf("-Xmx512m"))
    outputFormats.set(listOf("HTML", "XML"))
    timestampedReports.set(false)
    mutationThreshold.set(80)
    coverageThreshold.set(90)
}

// Rewrites the winnable deal lists (WinnableDealsGenerator), outside the test task, where the search ran far slower.
tasks.register<JavaExec>("generateDeals") {
    classpath = sourceSets["test"].runtimeClasspath
    mainClass.set("io.github.vinaooo.solo.domain.deal.WinnableDealsGenerator")
    args(layout.projectDirectory.dir("src/main/resources/deals").asFile.path)
}
